# Generated by Django 4.1.6 on 2024-05-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookselv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='previews/'),
        ),
    ]
